// Generate the parts of docs/STATUS.md that would otherwise drift.
//
//   node tools/gen-status.mjs            # print the block to stdout
//   node tools/gen-status.mjs --write    # rewrite it in docs/STATUS.md
//   node tools/gen-status.mjs --check    # fail if docs/STATUS.md is stale (this is what CI runs)
//
// Two kinds of fact live in the generated block, and both are computed rather than typed:
//
//   * which mechanics are shipped and which are engine-only, from src/engine/mechanics.js
//     crossed with the levels that actually use them
//   * the check counts, from a real run of the suite (with --report)
//
// `--check` also verifies the totals quoted in README.md and docs/PLAN.md, because those are
// the numbers a human reads first and the ones that have already gone wrong twice.

import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { MECHANICS, mechanicsOf } from '../src/engine/mechanics.js';
import { LEVELS } from '../src/engine/levels.js';

const ROOT = path.join(import.meta.dirname, '..');
const STATUS = path.join(ROOT, 'docs', 'STATUS.md');
const START = '<!-- generated:mechanics -->';
const END = '<!-- /generated:mechanics -->';

const argv = process.argv.slice(2);
const wantsWrite = argv.includes('--write');
const wantsCheck = argv.includes('--check');

/** Run the suite and read its machine-readable summary. */
function runSuite() {
  const res = spawnSync(process.execPath, ['tests/run.js', '--report'], {
    cwd: ROOT,
    encoding: 'utf8',
  });
  const line = res.stdout.trim().split('\n').filter((l) => l.startsWith('{')).pop();
  if (!line) throw new Error('tests/run.js did not print a report line');
  const report = JSON.parse(line);
  if (report.fail) throw new Error(`the suite is not green (${report.fail} failed), fix that first`);
  return report;
}

function tableFor(rows) {
  const head = '| Mechanic | Engine | Renders | Tuning | In a level |\n| --- | --- | --- | --- | --- |';
  const body = rows.map(({ mechanic: m, users }) => {
    const renders = { mesh: 'mesh', painted: 'painted cells', none: '**nothing**' }[m.render];
    const tuning = m.tuning.length ? m.tuning.map((p) => `\`${p}\``).join(', ') : '—';
    const inLevel = users.length ? users.join(', ') : '**no level yet**';
    return `| ${m.label} | yes | ${renders} | ${tuning} | ${inLevel} |`;
  });
  return [head, ...body].join('\n');
}

function block(report) {
  const built = LEVELS.map((spec) => ({ id: spec.id ?? spec.name, spec }));
  const withUsers = MECHANICS.map((m) => ({
    mechanic: m,
    users: built.filter(({ spec }) => mechanicsOf(spec).some((x) => x.key === m.key)).map((b) => b.id),
  }));

  const shipped = withUsers.filter((r) => r.users.length);
  const engineOnly = withUsers.filter((r) => !r.users.length);
  const gap = engineOnly.filter((r) => r.mechanic.render === 'none');

  const suites = report.suites
    .map((s) => `| \`${s.file}\` | ${s.checks} |`)
    .join('\n');

  const lines = [
    START,
    `_Generated by \`node tools/gen-status.mjs --write\`. ${report.pass} checks in ${report.suites.length} suites; checked in CI by \`--check\`._`,
    '',
    `### Shipped: a built level uses it (${shipped.length})`,
    '',
    tableFor(shipped),
    '',
    `### Built and tested, in no level yet (${engineOnly.length})`,
    '',
    tableFor(engineOnly),
  ];

  if (gap.length) {
    lines.push(
      '',
      `**Physics without a picture:** ${gap.map((r) => r.mechanic.label).join(', ')}. ` +
        '`tests/mechanics.test.js` fails the moment an authored level uses one of these, so this cannot reach a player.',
    );
  }

  // Notes are printed once; the gap ones already have their own paragraph above.
  const gapKeys = new Set(gap.map((r) => r.mechanic.key));
  for (const { mechanic: m } of withUsers) {
    if (m.note && !gapKeys.has(m.key)) lines.push('', `- **${m.label}** — ${m.note}`);
  }

  lines.push(
    '',
    '### The suite',
    '',
    '| Suite | Checks |',
    '| --- | --- |',
    suites,
    '',
    `**${report.pass} checks, ${report.suites.length} suites, 0 failures.** This table is the run that generated this block.`,
    '',
    END,
  );

  return lines.join('\n');
}

/** Replace the marked block in a text file. */
function splice(text, replacement) {
  const a = text.indexOf(START);
  const b = text.indexOf(END);
  if (a < 0 || b < 0) throw new Error(`docs/STATUS.md is missing ${START} / ${END}`);
  return text.slice(0, a) + replacement + text.slice(b + END.length);
}

/** The totals each human-facing doc quotes, and the pattern that finds them. */
const TOTALS = [
  { file: 'README.md', re: /(\d+) headless checks/ },
  { file: 'docs/STATUS.md', re: /(\d+) checks, (\d+) suites, 0 failures/ },
  { file: 'docs/PLAN.md', re: /(\d+) checks pass in/ },
];

if (wantsWrite || wantsCheck) {
  const report = runSuite();
  const blockText = block(report);
  const text = fs.readFileSync(STATUS, 'utf8');
  const spliced = splice(text, blockText);

  if (wantsWrite) {
    if (spliced !== text) fs.writeFileSync(STATUS, spliced);
    console.log(`docs/STATUS.md ${spliced === text ? 'already current' : 'updated'} (${report.pass} checks)`);
  }

  if (wantsCheck) {
    const problems = [];
    if (spliced !== text) problems.push('docs/STATUS.md: the generated block is stale (run --write)');
    for (const { file, re } of TOTALS) {
      const body = fs.readFileSync(path.join(ROOT, file), 'utf8');
      const m = body.match(re);
      if (!m) {
        problems.push(`${file}: no summary matching ${re} — the doc stopped quoting a count`);
        continue;
      }
      if (Number(m[1]) !== report.pass) problems.push(`${file}: says ${m[1]} checks, the suite has ${report.pass}`);
      if (m[2] && Number(m[2]) !== report.suites.length) {
        problems.push(`${file}: says ${m[2]} suites, the suite has ${report.suites.length}`);
      }
    }
    if (problems.length) {
      console.error(problems.map((p) => `  ${p}`).join('\n'));
      process.exit(1);
    }
    console.log(`docs are current: ${report.pass} checks in ${report.suites.length} suites`);
  }
} else {
  console.log(block(runSuite()));
}
